# Generated by Django 5.0 on 2024-08-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('does_not_equal', 'Does not equal'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('greater_than', 'Greater than'), ('less_than', 'Less than'), ('greater_than_or_equals', 'Greater than or equals'), ('less_than_or_equals', 'Less than or equals'), ('is_true', 'Is true'), ('is_false', 'Is false')], max_length=50)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('dependency_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='fieldtype',
            options={'verbose_name': 'Field Type', 'verbose_name_plural': 'Field Types'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name_plural': 'Surveys'},
        ),
        migrations.AddField(
            model_name='field',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='surveys_builder.fieldtype'),
        ),
        migrations.AlterField(
            model_name='field',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='field',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='surveys_builder.section'),
        ),
        migrations.AlterField(
            model_name='option',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys_builder.field'),
        ),
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys_builder.survey'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['section', 'order'], name='surveys_bui_section_b9133d_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['survey', 'order'], name='surveys_bui_survey__9018b6_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['title', 'id'], name='surveys_bui_title_fddce7_idx'),
        ),
        migrations.AddField(
            model_name='condition',
            name='source_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='surveys_builder.field'),
        ),
        migrations.AddField(
            model_name='conditiondependency',
            name='affected_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_logic', to='surveys_builder.field'),
        ),
        migrations.AddField(
            model_name='conditiondependency',
            name='affected_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_logic', to='surveys_builder.section'),
        ),
        migrations.AddField(
            model_name='conditiondependency',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='surveys_builder.condition'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='source_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='surveys_builder.field'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='target_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='surveys_builder.field'),
        ),
    ]
